spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pizza
    username: postgres
    password: root
  jpa:
    show-sql: true

#logging:
#  file:
#    name: hello-liquibase.log
#  level:
#    spring: INFO
